//user
export const USER_LOGGED_IN = "USER_LOGGED_IN";
export const USER_LOGGED_OUT = "USER_LOGGED_OUT";

//import
export const SHOW_IMPORT_CLIENT = "SHOW_IMPORT_CLIENT";
export const SHOW_IMPORT_TRANSACTION = "SHOW_IMPORT_TRANSACTION";
export const NEW_IMPORT_CLIENT = "NEW_IMPORT_CLIENT";
export const NEW_IMPORT_TRANSACTION = "NEW_IMPORT_TRANSACTION";

//mapping
export const NEW_MAPPING = "NEW_MAPPING";
export const ALL_MAPPING = "ALL_MAPPING";
export const SAVE_MAPPING = "SAVE_MAPPING";

//field
export const SELECT_FIELDS_FOR_MAPPING = "SELECT_FIELDS_FOR_MAPPING";
